name: omni-reporter-gradle-plugin

on:
  push:
    branches: [ main ]
  pull_request_target:
    types:
      - closed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build and Create Local Plugin
      run: gradle clean build test publishToMavenLocal   
      
    - name: Create new Build Script
      run: sed 's+//++g' build.gradle.kts  > plugin.build.gradle.kts
      
    - name: Test New Build Coverage Run
      run: ./gradlew -c plugin.settings.gradle.kts build
      env:
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
         CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
